name: Publish (Development)
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubicloud
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: "3.48.0"